[package]
name = "slkrd"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.11.6"
tokio = { version = "1", features = ["full"] }
rand = "0.9"
structopt = "0.3"
rcgen = "0.13.2"
rustls = "0.23.22"
async-trait = "0.1"