[package]
name = "slkrd"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
rand = "0.9"
ssh2 = "0.9"
tokio = { version = "1.0", features = ["full"] }
webrtc = "0.12.0"
bytes = "1.0"
serde_json = "1.0"
