[package]
name = "slkrd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
webrtc = "0.12"
clap = "4.0"
indicatif = "0.17"
futures = "0.3"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.4"
