[package]
name = "slkrd"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"
ssh2 = "0.9"
tokio = { version = "1.0", features = ["full"] }
get_if_addrs = "0.5.3"  # Add this line
socket2 = "0.5.8"
clap = { version = "4.5.28", features = ["derive"] }
indicatif = "0.17.11"

